

export const FETCH_BANNERDATA_RESULT      =  'FETCH_BANNERDATA_RESULT';
export const RECEIVE_BANNERDATA_RESULT    =  'RECEIVE_BANNERDATA_RESULT';

export const FETCH_HOTLIVEDATA_RESULT      =  'FETCH_HOTLIVEDATA_RESULT';
export const RECEIVE_HOTLIVEDATA_RESULT    =  'RECEIVE_HOTLIVEDATA_RESULT';

export const FETCH_GIFTDATA_RESULT      =  'FETCH_GIFTDATA_RESULT';
export const RECEIVE_GIFTDATA_RESULT    =  'RECEIVE_GIFTDATA_RESULT';

export const FETCH_NEARDATA_RESULT      =  'FETCH_NEARDATA_RESULT';
export const RECEIVE_NEARDATA_RESULT    =  'RECEIVE_NEARDATA_RESULT';